controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_forgot_password_request:
    path: '/forgot-password'
    controller: 'App\Controller\ResetPasswordController::requestPasswordReset'